(
var idDict = (
	name: "LPF",
	symbol: \mhLPF,
	category: \equalisation,
	type: \effect,
	tunable: false,
	dependencies: nil,
	numChannels: 2,

	params: [

		(
			type: \in,
			symbol: \inBus,
			numChannels: 2,
			text: "in",
		),

		(
			type: \continuous,
			symbol: \freq,
			default: 5000,
			min: 20,
			max: 20000,
			scale: \exp,
			text: "freq",
			// DisplayFunc
			displayFunction: { |value|
				value = value.asInteger;
				value = value.asString ++ "hz";
				value
			},
		),
	]
);

SynthDef(\mhLPF, { |out = 0, inBus, freq = 5000|
	var snd = In.ar(inBus, 2);
	snd = LPF.ar(snd, freq);
	Out.ar(out, snd);
}).add;

idDict
)